services:
  go:
    env_file: .env
    environment:
      - API_PORT=8080
    image: golang:1.25
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    networks:
      - public
    working_dir: /usr/src/app
    command: go run .
    # depends_on:
    #   elasticsearch:
    #     condition: service_healthy

  mysql:
    environment:
      - MYSQL_DATABASE=datacite
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    image: mysql:8.0
    ports:
      - "3311:3306"
    networks:
      - public
    profiles:
      - test

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: changeme
      xpack.security.enabled: "false"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    networks:
      - public
    healthcheck:
      test: curl -f http://elastic:changeme@elasticsearch:9200
      interval: 10s
      timeout: 1s
    profiles:
      - test

  memcached:
    image: memcached:1.4.31
    ports:
      - "11211:11211"
    networks:
      - public
    profiles:
      - test

networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.5.0/24
          gateway: 172.28.5.1
