name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/web/Dockerfile
            image: ghcr.io/${{ github.repository }}web
          # - dockerfile: ./docker/worker/Dockerfile
          #   image: ghcr.io/${{ github.repository }}worker
    uses: ./.github/workflows/build_docker.yml
    with:
      image: ${{ matrix.image }}
      dockerfile: ${{ matrix.dockerfile }}

  deploy-api:
    needs: [build]
    uses: ./.github/workflows/deployment.yml
    with:
      versionvar_filename: metadata-completeness
      service_name: metadata-completeness
      env_name: stage
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
